server:
  servlet:
    context-path: /wzhks
  port: 9080

mybatis-plus:
  configuration:
    cache-enabled: false
  mapper-locations: classpath:mapping/*Mapper.xml
  typeAliasesPackage: com.abc.wzhks.web.model
  global-config:
    banner: off

spring:
  main:
    banner-mode: "OFF"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wzhks?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: wzhks
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数量
      minimum-idle: 3
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

shiro:
  shiroSessionOutTime: 20

#自定义
custom:
  kcmc: 模拟练习场
  ktmc: 模拟练习场
  kcdd: 模拟
  kcdm: AA001
  jyw: ACD45702551B170D4E272DE2B919F69966E0491BF7FAD90EB6DA560AE23B059E17A296CBE98E
  ksip: 10.100.0.1
  jzip: 10.100.0.253

